### ISSUE TITLE
Targeted ROS versions

### ISSUE THREAD

**Issue by gavanderhoorn** [Kawasaki-Robotics/khi_robot#3]
The readme states:

> ROS distribution `Kinetic` is supported.

but the MoveIt configuration and the `_description` packages give the impression that Indigo was/is also supported (because of [this](https://github.com/Kawasaki-Robotics/khi_robot/blob/cbfa6eac6a313ac281135328f00d304fabfc3fe4/duaro_description/urdf/duaro.urdf.xacro#L7) in the `duaro_description` pkg, and the `kConfigDefault` on the planner names in `duaro_moveit_config` ([here](https://github.com/Kawasaki-Robotics/khi_robot/blob/cbfa6eac6a313ac281135328f00d304fabfc3fe4/duaro_moveit_config/config/ompl_planning.yaml))).

Should Indigo support be maintained?

**Comment by matsui-hiro** [comment]
Indigo is not supported because we evaluated  for actual robot only with Kinetic.
I think that the simulator can be used with also Indigo but didn't try yet.
I'm sorry that there is no support plan for now.

**Comment by gavanderhoorn** [comment]
> Indigo is not supported because we evaluated for actual robot only with Kinetic.
> I think that the simulator can be used with also Indigo but didn't try yet.

Clear. Thanks.

> I'm sorry that there is no support plan for now.

No need to apologise. I don't use Indigo, but just wanted to make sure before changing things to be compatible with Kinetic (and newer) releases only.
