### ISSUE TITLE
request for melodic release

### ISSUE THREAD

**Issue by k-okada** [Kawasaki-Robotics/khi_robot#49]
@d-nakamichi @matsui-hiro Could you release khi_robot to melodic? We have confiremd it is working on melodic as it is with @sktometometo

Cc: @n-ando

**Comment by d-nakamichi** [comment]
We also confirmed it with melodic.
OK, we'll make a plan to release the current revision to Melodic/Kinetic distro and do it by this month.

**Comment by k-okada** [comment]
@d-nakamichi Thakn you!

**Comment by d-nakamichi** [comment]
Now, I've released v1.2.0 for Kinetic/Melodic
https://wiki.ros.org/khi_robot

**Comment by k-okada** [comment]
thank you!
--
◉ Kei Okada



2021年2月25日(木) 12:32 Daisuke NAKAMICHI <notifications@github.com>:

**Comment by d-nakamichi** [comment]
If there is no additional request, could you close this issue?

**Comment by k-okada** [comment]
hoep we could have rs003 in melodic https://github.com/Kawasaki-Robotics/khi_robot/issues/45, but closeing this issue for now.
