### ISSUE TITLE
How to make the robot active again after sending HOLD with khi_robot_command_service

### ISSUE THREAD

**Issue by wakasaki41** [Kawasaki-Robotics/khi_robot#73]
We are working with RS080n and tried to use khi_robot_command_service to send HOLD and CONTINUE signals from the safety system.
The HOLD signal worked well, but we could not get it back to the active state with the CONTINUE signal.

How can I transition the robot to the active state?

**Comment by matsui-hiro** [comment]
When stopping the robot,  you can use `type : as`  `cmd: HOLD` of khi_robot_command_service  .

But to reactivate driver, please use `type : driver` (not `type : as`)  .

> string type -> "driver"
> string cmd -> "restart"

Sending `cmd: restart`  activates driver.

Please see [this](https://github.com/Kawasaki-Robotics/khi_robot/blob/master/docs/ConnectingRealRobot.md#restart-driver-for-active) for details.

**Comment by wakasaki41** [comment]
Thank you very much.
I have tried the reboot command as it is.
What kind of error is this?
```
$ rosservice call /khi_robot_command_service "type: 'driver'
cmd: 'restert'"
driver_ret: -4096
as_ret: 0
cmd_ret: "INVALID CMD"
```

**Comment by matsui-hiro** [comment]
Hi @wakasaki41,

From the error log, I found a spelling mistake.
Please execute `cmd:restart` not `cmd:restert`.

**Comment by wakasaki41** [comment]
Thank you very much , It worked ‼!
